#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Flash option bytes (MS32C001B, mapped at 0x1FFF0040)"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Configbytes { ptr : * mut u8 } unsafe impl Send for Configbytes { } unsafe impl Sync for Configbytes { } impl Configbytes { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "User option bytes and complements (loaded into FLASH_OPTR at reset)"]
# [inline (always)]
pub const fn optr (self) -> crate :: common :: Reg < regs :: Optr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "SDK area address option bytes and complements (loaded into FLASH_SDKR at reset)"]
# [inline (always)]
pub const fn sdkr (self) -> crate :: common :: Reg < regs :: Sdkr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "WRP address option bytes and complements (loaded into FLASH_WRPR at reset)"]
# [inline (always)]
pub const fn wrpr (self) -> crate :: common :: Reg < regs :: Wrpr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } } pub mod regs { # [doc = "User option bytes and complements"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Optr (pub u32) ; impl Optr { # [doc = "Read protection level (0xAA: level 0, no protection; otherwise: level 1, protection active)"]
# [inline (always)]
pub const fn rdp (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Read protection level (0xAA: level 0, no protection; otherwise: level 1, protection active)"]
# [inline (always)]
pub fn set_rdp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "BOR enable (0: disabled; 1: enabled, BOR_LEV active)"]
# [inline (always)]
pub const fn bor_en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "BOR enable (0: disabled; 1: enabled, BOR_LEV active)"]
# [inline (always)]
pub fn set_bor_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "BOR threshold level (000: 2.2V/2.1V ... 111: 3.6V/3.5V)"]
# [inline (always)]
pub const fn bor_lev (& self) -> u8 { let val = (self . 0 >> 9usize) & 0x07 ; val as u8 } # [doc = "BOR threshold level (000: 2.2V/2.1V ... 111: 3.6V/3.5V)"]
# [inline (always)]
pub fn set_bor_lev (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 9usize)) | (((val as u32) & 0x07) << 9usize) ; } # [doc = "IWDG mode (0: hardware watchdog; 1: software watchdog)"]
# [inline (always)]
pub const fn iwdg_sw (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "IWDG mode (0: hardware watchdog; 1: software watchdog)"]
# [inline (always)]
pub fn set_iwdg_sw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "NRST pin mode (0: reset input only; 1: GPIO function)"]
# [inline (always)]
pub const fn nrst_mode (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "NRST pin mode (0: reset input only; 1: GPIO function)"]
# [inline (always)]
pub fn set_nrst_mode (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "IWDG behavior in Stop mode (0: freeze; 1: keep running)"]
# [inline (always)]
pub const fn iwdg_stop (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "IWDG behavior in Stop mode (0: freeze; 1: keep running)"]
# [inline (always)]
pub fn set_iwdg_stop (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Complemented read protection level"]
# [inline (always)]
pub const fn nrdp (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Complemented read protection level"]
# [inline (always)]
pub fn set_nrdp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Complemented BOR enable"]
# [inline (always)]
pub const fn nbor_en (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Complemented BOR enable"]
# [inline (always)]
pub fn set_nbor_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Complemented BOR threshold level"]
# [inline (always)]
pub const fn nbor_lev (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x07 ; val as u8 } # [doc = "Complemented BOR threshold level"]
# [inline (always)]
pub fn set_nbor_lev (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 25usize)) | (((val as u32) & 0x07) << 25usize) ; } # [doc = "Complemented IWDG mode"]
# [inline (always)]
pub const fn niwdg_sw (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Complemented IWDG mode"]
# [inline (always)]
pub fn set_niwdg_sw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Complemented NRST pin mode"]
# [inline (always)]
pub const fn nnrst_mode (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Complemented NRST pin mode"]
# [inline (always)]
pub fn set_nnrst_mode (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Complemented IWDG Stop mode behavior"]
# [inline (always)]
pub const fn niwdg_stop (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Complemented IWDG Stop mode behavior"]
# [inline (always)]
pub fn set_niwdg_stop (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Optr { # [inline (always)]
fn default () -> Optr { Optr (0) } } # [doc = "SDK area address option bytes and complements"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sdkr (pub u32) ; impl Sdkr { # [doc = "SDK area start address (step = 1 KB)"]
# [inline (always)]
pub const fn sdk_strt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "SDK area start address (step = 1 KB)"]
# [inline (always)]
pub fn set_sdk_strt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "SDK area end address (step = 1 KB)"]
# [inline (always)]
pub const fn sdk_end (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "SDK area end address (step = 1 KB)"]
# [inline (always)]
pub fn set_sdk_end (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "Complemented SDK area start address"]
# [inline (always)]
pub const fn nsdk_strt (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "Complemented SDK area start address"]
# [inline (always)]
pub fn set_nsdk_strt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "Complemented SDK area end address"]
# [inline (always)]
pub const fn nsdk_end (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "Complemented SDK area end address"]
# [inline (always)]
pub fn set_nsdk_end (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } } impl Default for Sdkr { # [inline (always)]
fn default () -> Sdkr { Sdkr (0) } } # [doc = "WRP address option bytes and complements"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wrpr (pub u32) ; impl Wrpr { # [doc = "Write protection bits (0: sector\\[y\\]
protected; 1: unprotected; y = 0..15)"]
# [inline (always)]
pub const fn wrp (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Write protection bits (0: sector\\[y\\]
protected; 1: unprotected; y = 0..15)"]
# [inline (always)]
pub fn set_wrp (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Complemented write protection bits"]
# [inline (always)]
pub const fn nwrp (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Complemented write protection bits"]
# [inline (always)]
pub fn set_nwrp (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Wrpr { # [inline (always)]
fn default () -> Wrpr { Wrpr (0) } } }