#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Cyclic redundancy check calculation unit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Crc { ptr : * mut u8 } unsafe impl Send for Crc { } unsafe impl Sync for Crc { } impl Crc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "CRC data register"]
# [inline (always)]
pub const fn dr (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "CRC independent data register"]
# [inline (always)]
pub const fn idr (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "CRC control register"]
# [inline (always)]
pub const fn cr (self) -> crate :: common :: Reg < regs :: Cr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } } pub mod regs { # [doc = "CRC control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr (pub u32) ; impl Cr { # [doc = "Reset bit. Writing 1 resets the CRC calculation unit to 0xFFFF_FFFF. No effect on the independent data register."]
# [inline (always)]
pub const fn reset (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Reset bit. Writing 1 resets the CRC calculation unit to 0xFFFF_FFFF. No effect on the independent data register."]
# [inline (always)]
pub fn set_reset (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for Cr { # [inline (always)]
fn default () -> Cr { Cr (0) } } }