#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Clock trimming controller."]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctc { ptr : * mut u8 } unsafe impl Send for Ctc { } unsafe impl Sync for Ctc { } impl Ctc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register 0."]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register 1."]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Status register."]
# [inline (always)]
pub const fn sr (self) -> crate :: common :: Reg < regs :: Sr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Interrupt clear register."]
# [inline (always)]
pub const fn intc (self) -> crate :: common :: Reg < regs :: Intc , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } } pub mod regs { # [doc = "Control register 0."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Clock OK interrupt enable."]
# [inline (always)]
pub const fn ckokie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Clock OK interrupt enable."]
# [inline (always)]
pub fn set_ckokie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Clock warning interrupt enable."]
# [inline (always)]
pub const fn ckwarnie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Clock warning interrupt enable."]
# [inline (always)]
pub fn set_ckwarnie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error interrupt enable."]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error interrupt enable."]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Reference signal presence interrupt enable."]
# [inline (always)]
pub const fn erefie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Reference signal presence interrupt enable."]
# [inline (always)]
pub fn set_erefie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Counter enable. While set, CTL1 cannot be modified."]
# [inline (always)]
pub const fn cnten (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Counter enable. While set, CTL1 cannot be modified."]
# [inline (always)]
pub fn set_cnten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Automatic trimming enable."]
# [inline (always)]
pub const fn autotrim (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Automatic trimming enable."]
# [inline (always)]
pub fn set_autotrim (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Software reference pulse. Cleared by hardware after the pulse is generated."]
# [inline (always)]
pub const fn swrefpul (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Software reference pulse. Cleared by hardware after the pulse is generated."]
# [inline (always)]
pub fn set_swrefpul (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "HSI48 clock trimming value. Hardware-controlled when AUTOTRIM is set."]
# [inline (always)]
pub const fn trimvalue (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x7f ; val as u8 } # [doc = "HSI48 clock trimming value. Hardware-controlled when AUTOTRIM is set."]
# [inline (always)]
pub fn set_trimvalue (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 8usize)) | (((val as u32) & 0x7f) << 8usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } # [doc = "Control register 1."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Counter reload value, captured on each reference pulse."]
# [inline (always)]
pub const fn rlvalue (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Counter reload value, captured on each reference pulse."]
# [inline (always)]
pub fn set_rlvalue (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Clock limit value. The counter compares against multiples of this limit."]
# [inline (always)]
pub const fn cklim (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Clock limit value. The counter compares against multiples of this limit."]
# [inline (always)]
pub fn set_cklim (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Reference signal prescaler."]
# [inline (always)]
pub const fn refpsc (& self) -> super :: vals :: Refpsc { let val = (self . 0 >> 24usize) & 0x07 ; super :: vals :: Refpsc :: from_bits (val as u8) } # [doc = "Reference signal prescaler."]
# [inline (always)]
pub fn set_refpsc (& mut self , val : super :: vals :: Refpsc) { self . 0 = (self . 0 & ! (0x07 << 24usize)) | (((val . to_bits () as u32) & 0x07) << 24usize) ; } # [doc = "Reference signal source selection."]
# [inline (always)]
pub const fn refsel (& self) -> super :: vals :: Refsel { let val = (self . 0 >> 28usize) & 0x03 ; super :: vals :: Refsel :: from_bits (val as u8) } # [doc = "Reference signal source selection."]
# [inline (always)]
pub fn set_refsel (& mut self , val : super :: vals :: Refsel) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val . to_bits () as u32) & 0x03) << 28usize) ; } # [doc = "Reference signal polarity."]
# [inline (always)]
pub const fn refpol (& self) -> super :: vals :: Refpol { let val = (self . 0 >> 31usize) & 0x01 ; super :: vals :: Refpol :: from_bits (val as u8) } # [doc = "Reference signal polarity."]
# [inline (always)]
pub fn set_refpol (& mut self , val : super :: vals :: Refpol) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val . to_bits () as u32) & 0x01) << 31usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } # [doc = "Interrupt clear register."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intc (pub u32) ; impl Intc { # [doc = "Clock OK flag clear."]
# [inline (always)]
pub const fn ckokic (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Clock OK flag clear."]
# [inline (always)]
pub fn set_ckokic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Clock warning flag clear."]
# [inline (always)]
pub const fn ckwarnic (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Clock warning flag clear."]
# [inline (always)]
pub fn set_ckwarnic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error flag clear."]
# [inline (always)]
pub const fn erric (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error flag clear."]
# [inline (always)]
pub fn set_erric (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Reference signal presence flag clear."]
# [inline (always)]
pub const fn erefic (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Reference signal presence flag clear."]
# [inline (always)]
pub fn set_erefic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for Intc { # [inline (always)]
fn default () -> Intc { Intc (0) } } # [doc = "Status register."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sr (pub u32) ; impl Sr { # [doc = "Clock OK flag. The counter was below 3 x CKLIM at the sync pulse."]
# [inline (always)]
pub const fn ckokif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Clock OK flag. The counter was below 3 x CKLIM at the sync pulse."]
# [inline (always)]
pub fn set_ckokif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Clock warning flag. The counter was between 3 x CKLIM and 128 x CKLIM at the sync pulse."]
# [inline (always)]
pub const fn ckwarnif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Clock warning flag. The counter was between 3 x CKLIM and 128 x CKLIM at the sync pulse."]
# [inline (always)]
pub fn set_ckwarnif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error flag."]
# [inline (always)]
pub const fn errif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error flag."]
# [inline (always)]
pub fn set_errif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Reference signal presence flag."]
# [inline (always)]
pub const fn erefif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Reference signal presence flag."]
# [inline (always)]
pub fn set_erefif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Clock error. The counter reached 128 x CKLIM at a sync pulse, indicating the trimmed clock is too slow."]
# [inline (always)]
pub const fn ckerr (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Clock error. The counter reached 128 x CKLIM at a sync pulse, indicating the trimmed clock is too slow."]
# [inline (always)]
pub fn set_ckerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Reference signal missing. No sync pulse was detected within 128 x CKLIM counter cycles while counting up."]
# [inline (always)]
pub const fn refmiss (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Reference signal missing. No sync pulse was detected within 128 x CKLIM counter cycles while counting up."]
# [inline (always)]
pub fn set_refmiss (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Trimming error. TRIMVALUE overflowed or underflowed during automatic trimming."]
# [inline (always)]
pub const fn trimerr (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Trimming error. TRIMVALUE overflowed or underflowed during automatic trimming."]
# [inline (always)]
pub fn set_trimerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Reference signal direction indicator."]
# [inline (always)]
pub const fn refdir (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Reference signal direction indicator."]
# [inline (always)]
pub fn set_refdir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Counter value captured on the last reference pulse."]
# [inline (always)]
pub const fn refcap (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Counter value captured on the last reference pulse."]
# [inline (always)]
pub fn set_refcap (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Sr { # [inline (always)]
fn default () -> Sr { Sr (0) } } } pub mod vals { # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Refpol { # [doc = "Reference edge is rising."]
RISINGEDGE = 0x0 , # [doc = "Reference edge is falling."]
FALLINGEDGE = 0x01 , } impl Refpol { # [inline (always)]
pub const fn from_bits (val : u8) -> Refpol { unsafe { core :: mem :: transmute (val & 0x01) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Refpol { # [inline (always)]
fn from (val : u8) -> Refpol { Refpol :: from_bits (val) } } impl From < Refpol > for u8 { # [inline (always)]
fn from (val : Refpol) -> u8 { Refpol :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Refpsc { # [doc = "Reference signal not divided."]
DIV1 = 0x0 , # [doc = "Reference signal divided by 2."]
DIV2 = 0x01 , # [doc = "Reference signal divided by 4."]
DIV4 = 0x02 , # [doc = "Reference signal divided by 8."]
DIV8 = 0x03 , # [doc = "Reference signal divided by 16."]
DIV16 = 0x04 , # [doc = "Reference signal divided by 32."]
DIV32 = 0x05 , # [doc = "Reference signal divided by 64."]
DIV64 = 0x06 , # [doc = "Reference signal divided by 128."]
DIV128 = 0x07 , } impl Refpsc { # [inline (always)]
pub const fn from_bits (val : u8) -> Refpsc { unsafe { core :: mem :: transmute (val & 0x07) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Refpsc { # [inline (always)]
fn from (val : u8) -> Refpsc { Refpsc :: from_bits (val) } } impl From < Refpsc > for u8 { # [inline (always)]
fn from (val : Refpsc) -> u8 { Refpsc :: to_bits (val) } } # [repr (u8)]
# [derive (Copy , Clone , Eq , PartialEq , Ord , PartialOrd)]
pub enum Refsel { # [doc = "GPIO input as reference signal."]
GPIO = 0x0 , # [doc = "LSE oscillator as reference signal."]
LSE = 0x01 , # [doc = "USB start-of-frame signal as reference signal."]
USBDSOF = 0x02 , _RESERVED_3 = 0x03 , } impl Refsel { # [inline (always)]
pub const fn from_bits (val : u8) -> Refsel { unsafe { core :: mem :: transmute (val & 0x03) } } # [inline (always)]
pub const fn to_bits (self) -> u8 { unsafe { core :: mem :: transmute (self) } } } impl From < u8 > for Refsel { # [inline (always)]
fn from (val : u8) -> Refsel { Refsel :: from_bits (val) } } impl From < Refsel > for u8 { # [inline (always)]
fn from (val : Refsel) -> u8 { Refsel :: to_bits (val) } } }