#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Hardware divider"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Div { ptr : * mut u8 } unsafe impl Send for Div { } unsafe impl Sync for Div { } impl Div { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Dividend register"]
# [inline (always)]
pub const fn dend (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Divisor register. Writing to it starts the division."]
# [inline (always)]
pub const fn sor (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Quotient register"]
# [inline (always)]
pub const fn quot (self) -> crate :: common :: Reg < u32 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Remainder register"]
# [inline (always)]
pub const fn remd (self) -> crate :: common :: Reg < u32 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Sign register"]
# [inline (always)]
pub const fn sign (self) -> crate :: common :: Reg < regs :: Sign , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Status register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } } pub mod regs { # [doc = "Sign register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sign (pub u32) ; impl Sign { # [doc = "Division sign. 0: unsigned division, 1: signed division."]
# [inline (always)]
pub const fn sign (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Division sign. 0: unsigned division, 1: signed division."]
# [inline (always)]
pub fn set_sign (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for Sign { # [inline (always)]
fn default () -> Sign { Sign (0) } } # [doc = "Status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "Division end flag. Set when the division is finished. Reading QUOT/REMD before this flag is set returns the result of the last completed division."]
# [inline (always)]
pub const fn div_end (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Division end flag. Set when the division is finished. Reading QUOT/REMD before this flag is set returns the result of the last completed division."]
# [inline (always)]
pub fn set_div_end (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Division by zero flag. Set when the divisor is 0. The operation ends immediately with QUOT and REMD both 0."]
# [inline (always)]
pub const fn div_zero (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Division by zero flag. Set when the divisor is 0. The operation ends immediately with QUOT and REMD both 0."]
# [inline (always)]
pub fn set_div_zero (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } }