#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Operational amplifiers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Opa { ptr : * mut u8 } unsafe impl Send for Opa { } unsafe impl Sync for Opa { } impl Opa { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "OPA output enable register"]
# [inline (always)]
pub const fn cr0 (self) -> crate :: common :: Reg < regs :: Cr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "OPA control register"]
# [inline (always)]
pub const fn cr1 (self) -> crate :: common :: Reg < regs :: Cr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } } pub mod regs { # [doc = "OPA output enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr0 (pub u32) ; impl Cr0 { # [doc = "OPAx output 1 enable. Routes the amplifier output to its dedicated pad. The output always reaches the ADC and COMP internally regardless of this bit."]
# [inline (always)]
pub const fn opaoen1 (& self , n : usize) -> bool { assert ! (n < 3usize) ; let offs = 1usize + n * 5usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "OPAx output 1 enable. Routes the amplifier output to its dedicated pad. The output always reaches the ADC and COMP internally regardless of this bit."]
# [inline (always)]
pub fn set_opaoen1 (& mut self , n : usize , val : bool) { assert ! (n < 3usize) ; let offs = 1usize + n * 5usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Cr0 { # [inline (always)]
fn default () -> Cr0 { Cr0 (0) } } # [doc = "OPA control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr1 (pub u32) ; impl Cr1 { # [doc = "OPAx enable"]
# [inline (always)]
pub const fn en (& self , n : usize) -> bool { assert ! (n < 3usize) ; let offs = 5usize + n * 1usize ; let val = (self . 0 >> offs) & 0x01 ; val != 0 } # [doc = "OPAx enable"]
# [inline (always)]
pub fn set_en (& mut self , n : usize , val : bool) { assert ! (n < 3usize) ; let offs = 5usize + n * 1usize ; self . 0 = (self . 0 & ! (0x01 << offs)) | (((val as u32) & 0x01) << offs) ; } } impl Default for Cr1 { # [inline (always)]
fn default () -> Cr1 { Cr1 (0) } } }