#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Power control."]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pwr { ptr : * mut u8 } unsafe impl Send for Pwr { } unsafe impl Sync for Pwr { } impl Pwr { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Power control register 1."]
# [inline (always)]
pub const fn cr1 (self) -> crate :: common :: Reg < regs :: Cr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } } pub mod regs { # [doc = "Power control register 1."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr1 (pub u32) ; impl Cr1 { # [doc = "MR Bias current."]
# [inline (always)]
pub const fn bias_cr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "MR Bias current."]
# [inline (always)]
pub fn set_bias_cr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "MR Bias current selection."]
# [inline (always)]
pub const fn bias_cr_sel (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "MR Bias current selection."]
# [inline (always)]
pub fn set_bias_cr_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Flash wait time after wakeup from the stop mode."]
# [inline (always)]
pub const fn fls_slptime (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "Flash wait time after wakeup from the stop mode."]
# [inline (always)]
pub fn set_fls_slptime (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Low-power run."]
# [inline (always)]
pub const fn lpr (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Low-power run."]
# [inline (always)]
pub fn set_lpr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } # [doc = "SRAM retention voltage control in stop mode."]
# [inline (always)]
pub const fn sram_retv (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "SRAM retention voltage control in stop mode."]
# [inline (always)]
pub fn set_sram_retv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "SRAM retention voltage control in deep-stop mode. Present on PY32L020."]
# [inline (always)]
pub const fn sram_retv_dlp (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "SRAM retention voltage control in deep-stop mode. Present on PY32L020."]
# [inline (always)]
pub fn set_sram_retv_dlp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "HSI open time control."]
# [inline (always)]
pub const fn hsion_ctrl (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "HSI open time control."]
# [inline (always)]
pub fn set_hsion_ctrl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } } impl Default for Cr1 { # [inline (always)]
fn default () -> Cr1 { Cr1 (0) } } }