#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Real-time clock."]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rtc { ptr : * mut u8 } unsafe impl Send for Rtc { } unsafe impl Sync for Rtc { } impl Rtc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register high."]
# [inline (always)]
pub const fn crh (self) -> crate :: common :: Reg < regs :: Crh , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register low."]
# [inline (always)]
pub const fn crl (self) -> crate :: common :: Reg < regs :: Crl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Prescaler load register high."]
# [inline (always)]
pub const fn prlh (self) -> crate :: common :: Reg < regs :: Prlh , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Prescaler load register low."]
# [inline (always)]
pub const fn prll (self) -> crate :: common :: Reg < regs :: Prll , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Prescaler divider register high."]
# [inline (always)]
pub const fn divh (self) -> crate :: common :: Reg < regs :: Divh , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Prescaler divider register low."]
# [inline (always)]
pub const fn divl (self) -> crate :: common :: Reg < regs :: Divl , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Counter register high."]
# [inline (always)]
pub const fn cnth (self) -> crate :: common :: Reg < regs :: Cnth , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Counter register low."]
# [inline (always)]
pub const fn cntl (self) -> crate :: common :: Reg < regs :: Cntl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Alarm register high."]
# [inline (always)]
pub const fn alrh (self) -> crate :: common :: Reg < regs :: Alrh , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Alarm register low."]
# [inline (always)]
pub const fn alrl (self) -> crate :: common :: Reg < regs :: Alrl , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Clock calibration and output configuration register."]
# [inline (always)]
pub const fn bkp_rtccr (self) -> crate :: common :: Reg < regs :: BkpRtccr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } } pub mod regs { # [doc = "Alarm register high."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Alrh (pub u32) ; impl Alrh { # [doc = "Alarm value, high bits (ALR\\[31:16\\])."]
# [inline (always)]
pub const fn alr (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Alarm value, high bits (ALR\\[31:16\\])."]
# [inline (always)]
pub fn set_alr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Alrh { # [inline (always)]
fn default () -> Alrh { Alrh (0) } } # [doc = "Alarm register low."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Alrl (pub u32) ; impl Alrl { # [doc = "Alarm value, low bits (ALR\\[15:0\\])."]
# [inline (always)]
pub const fn alr (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Alarm value, low bits (ALR\\[15:0\\])."]
# [inline (always)]
pub fn set_alr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Alrl { # [inline (always)]
fn default () -> Alrl { Alrl (0) } } # [doc = "Clock calibration and output configuration register."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct BkpRtccr (pub u32) ; impl BkpRtccr { # [doc = "Calibration value. Slows the clock by CAL x 1/2^20, up to 121 ppm."]
# [inline (always)]
pub const fn cal (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "Calibration value. Slows the clock by CAL x 1/2^20, up to 121 ppm."]
# [inline (always)]
pub fn set_cal (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } # [doc = "Calibration clock output. When set, outputs the RTC clock divided by 64."]
# [inline (always)]
pub const fn cco (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Calibration clock output. When set, outputs the RTC clock divided by 64."]
# [inline (always)]
pub fn set_cco (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Second or alarm pulse output enable."]
# [inline (always)]
pub const fn asoe (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Second or alarm pulse output enable."]
# [inline (always)]
pub fn set_asoe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Second or alarm pulse output selection. 0: second pulse; 1: alarm pulse."]
# [inline (always)]
pub const fn asos (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Second or alarm pulse output selection. 0: second pulse; 1: alarm pulse."]
# [inline (always)]
pub fn set_asos (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } } impl Default for BkpRtccr { # [inline (always)]
fn default () -> BkpRtccr { BkpRtccr (0) } } # [doc = "Counter register high."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cnth (pub u32) ; impl Cnth { # [doc = "Counter value, high bits (CNT\\[31:16\\])."]
# [inline (always)]
pub const fn cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Counter value, high bits (CNT\\[31:16\\])."]
# [inline (always)]
pub fn set_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Cnth { # [inline (always)]
fn default () -> Cnth { Cnth (0) } } # [doc = "Counter register low."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cntl (pub u32) ; impl Cntl { # [doc = "Counter value, low bits (CNT\\[15:0\\])."]
# [inline (always)]
pub const fn cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Counter value, low bits (CNT\\[15:0\\])."]
# [inline (always)]
pub fn set_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Cntl { # [inline (always)]
fn default () -> Cntl { Cntl (0) } } # [doc = "Control register high."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Crh (pub u32) ; impl Crh { # [doc = "Second interrupt enable."]
# [inline (always)]
pub const fn secie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Second interrupt enable."]
# [inline (always)]
pub fn set_secie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Alarm interrupt enable."]
# [inline (always)]
pub const fn alrie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Alarm interrupt enable."]
# [inline (always)]
pub fn set_alrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Overflow interrupt enable."]
# [inline (always)]
pub const fn owie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Overflow interrupt enable."]
# [inline (always)]
pub fn set_owie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for Crh { # [inline (always)]
fn default () -> Crh { Crh (0) } } # [doc = "Control register low."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Crl (pub u32) ; impl Crl { # [doc = "Second flag. Set by hardware once per prescaler period; cleared by writing 0."]
# [inline (always)]
pub const fn secf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Second flag. Set by hardware once per prescaler period; cleared by writing 0."]
# [inline (always)]
pub fn set_secf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Alarm flag. Set by hardware when the counter reaches the alarm value; cleared by writing 0."]
# [inline (always)]
pub const fn alrf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Alarm flag. Set by hardware when the counter reaches the alarm value; cleared by writing 0."]
# [inline (always)]
pub fn set_alrf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Overflow flag. Set by hardware when the counter overflows; cleared by writing 0."]
# [inline (always)]
pub const fn owf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Overflow flag. Set by hardware when the counter overflows; cleared by writing 0."]
# [inline (always)]
pub fn set_owf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Registers synchronized flag. Set by hardware once CNT and DIV have been synchronized; cleared by writing 0."]
# [inline (always)]
pub const fn rsf (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Registers synchronized flag. Set by hardware once CNT and DIV have been synchronized; cleared by writing 0."]
# [inline (always)]
pub fn set_rsf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Configuration flag. Set to enter configuration mode before writing PRL, CNT, ALR or BKP_RTCCR; clear it to commit."]
# [inline (always)]
pub const fn cnf (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Configuration flag. Set to enter configuration mode before writing PRL, CNT, ALR or BKP_RTCCR; clear it to commit."]
# [inline (always)]
pub fn set_cnf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "RTC operation off. Reads 1 when the last write has completed and a new write may start. Reset value is 1."]
# [inline (always)]
pub const fn rtoff (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "RTC operation off. Reads 1 when the last write has completed and a new write may start. Reset value is 1."]
# [inline (always)]
pub fn set_rtoff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for Crl { # [inline (always)]
fn default () -> Crl { Crl (0) } } # [doc = "Prescaler divider register high."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Divh (pub u32) ; impl Divh { # [doc = "Current prescaler divider value, high bits (DIV\\[19:16\\])."]
# [inline (always)]
pub const fn div (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Current prescaler divider value, high bits (DIV\\[19:16\\])."]
# [inline (always)]
pub fn set_div (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } } impl Default for Divh { # [inline (always)]
fn default () -> Divh { Divh (0) } } # [doc = "Prescaler divider register low."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Divl (pub u32) ; impl Divl { # [doc = "Current prescaler divider value, low bits (DIV\\[15:0\\])."]
# [inline (always)]
pub const fn div (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Current prescaler divider value, low bits (DIV\\[15:0\\])."]
# [inline (always)]
pub fn set_div (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Divl { # [inline (always)]
fn default () -> Divl { Divl (0) } } # [doc = "Prescaler load register high."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Prlh (pub u32) ; impl Prlh { # [doc = "Prescaler reload value, high bits (PRL\\[19:16\\])."]
# [inline (always)]
pub const fn prl (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Prescaler reload value, high bits (PRL\\[19:16\\])."]
# [inline (always)]
pub fn set_prl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } } impl Default for Prlh { # [inline (always)]
fn default () -> Prlh { Prlh (0) } } # [doc = "Prescaler load register low."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Prll (pub u32) ; impl Prll { # [doc = "Prescaler reload value, low bits (PRL\\[15:0\\])."]
# [inline (always)]
pub const fn prl (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Prescaler reload value, low bits (PRL\\[15:0\\])."]
# [inline (always)]
pub fn set_prl (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Prll { # [inline (always)]
fn default () -> Prll { Prll (0) } } }