#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Unique Device ID."]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Uid { ptr : * mut u8 } unsafe impl Send for Uid { } unsafe impl Sync for Uid { } impl Uid { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Factory programmed 96-bit unique device identifier words."]
# [inline (always)]
pub const fn uid (self , n : usize) -> crate :: common :: Reg < u32 , crate :: common :: R > { assert ! (n < 3usize) ; unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize + n * 4usize) as _) } } # [doc = "UID Word 0 (Offset 0x00)."]
# [inline (always)]
pub const fn word0 (self) -> crate :: common :: Reg < regs :: UidWord0 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "UID Word 1 (Offset 0x04)."]
# [inline (always)]
pub const fn word1 (self) -> crate :: common :: Reg < regs :: UidWord1 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "UID Word 2 (Offset 0x08)."]
# [inline (always)]
pub const fn word2 (self) -> crate :: common :: Reg < regs :: UidWord2 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "UID Word 3 (Offset 0x0C)."]
# [inline (always)]
pub const fn word3 (self) -> crate :: common :: Reg < regs :: UidWord3 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } } pub mod regs { # [doc = "Lot Number (Bytes 0-3)."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UidWord0 (pub u32) ; impl UidWord0 { # [doc = "Lot Number ASCII Code (Byte 0)."]
# [inline (always)]
pub const fn lot_num_ascii_0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 0)."]
# [inline (always)]
pub fn set_lot_num_ascii_0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Lot Number ASCII Code (Byte 1)."]
# [inline (always)]
pub const fn lot_num_ascii_1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 1)."]
# [inline (always)]
pub fn set_lot_num_ascii_1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Lot Number ASCII Code (Byte 2)."]
# [inline (always)]
pub const fn lot_num_ascii_2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 2)."]
# [inline (always)]
pub fn set_lot_num_ascii_2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Lot Number ASCII Code (Byte 3)."]
# [inline (always)]
pub const fn lot_num_ascii_3 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 3)."]
# [inline (always)]
pub fn set_lot_num_ascii_3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for UidWord0 { # [inline (always)]
fn default () -> UidWord0 { UidWord0 (0) } } # [doc = "Wafer Number and Lot Number (Bytes 4-7)."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UidWord1 (pub u32) ; impl UidWord1 { # [doc = "Wafer Number."]
# [inline (always)]
pub const fn wafer_num (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Wafer Number."]
# [inline (always)]
pub fn set_wafer_num (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Lot Number ASCII Code (Byte 4)."]
# [inline (always)]
pub const fn lot_num_ascii_4 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 4)."]
# [inline (always)]
pub fn set_lot_num_ascii_4 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Lot Number ASCII Code (Byte 5)."]
# [inline (always)]
pub const fn lot_num_ascii_5 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 5)."]
# [inline (always)]
pub fn set_lot_num_ascii_5 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Lot Number ASCII Code (Byte 6)."]
# [inline (always)]
pub const fn lot_num_ascii_6 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Lot Number ASCII Code (Byte 6)."]
# [inline (always)]
pub fn set_lot_num_ascii_6 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for UidWord1 { # [inline (always)]
fn default () -> UidWord1 { UidWord1 (0) } } # [doc = "Coordinates and Internal Coding (Bytes 8-11)."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UidWord2 (pub u32) ; impl UidWord2 { # [doc = "Internal Coding (Byte 0)."]
# [inline (always)]
pub const fn internal_code_0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Internal Coding (Byte 0)."]
# [inline (always)]
pub fn set_internal_code_0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Y Coordinate Low bits."]
# [inline (always)]
pub const fn y_coord_low (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Y Coordinate Low bits."]
# [inline (always)]
pub fn set_y_coord_low (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "X Coordinate Low bits."]
# [inline (always)]
pub const fn x_coord_low (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "X Coordinate Low bits."]
# [inline (always)]
pub fn set_x_coord_low (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "X Coordinate High bits."]
# [inline (always)]
pub const fn x_coord_high (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "X Coordinate High bits."]
# [inline (always)]
pub fn set_x_coord_high (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [doc = "Y Coordinate High bits."]
# [inline (always)]
pub const fn y_coord_high (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x0f ; val as u8 } # [doc = "Y Coordinate High bits."]
# [inline (always)]
pub fn set_y_coord_high (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize) ; } } impl Default for UidWord2 { # [inline (always)]
fn default () -> UidWord2 { UidWord2 (0) } } # [doc = "Internal Coding and Fixed Code (Bytes 12-15)."]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UidWord3 (pub u32) ; impl UidWord3 { # [doc = "Fixed Code (0x78)."]
# [inline (always)]
pub const fn fixed_code (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Fixed Code (0x78)."]
# [inline (always)]
pub fn set_fixed_code (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Internal Coding (Byte 1)."]
# [inline (always)]
pub const fn internal_code_1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Internal Coding (Byte 1)."]
# [inline (always)]
pub fn set_internal_code_1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Internal Coding (Byte 2)."]
# [inline (always)]
pub const fn internal_code_2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Internal Coding (Byte 2)."]
# [inline (always)]
pub fn set_internal_code_2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Internal Coding (Byte 3)."]
# [inline (always)]
pub const fn internal_code_3 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Internal Coding (Byte 3)."]
# [inline (always)]
pub fn set_internal_code_3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for UidWord3 { # [inline (always)]
fn default () -> UidWord3 { UidWord3 (0) } } }