#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Voltage reference buffer (MS32C001B)"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Vref { ptr : * mut u8 } unsafe impl Send for Vref { } unsafe impl Sync for Vref { } impl Vref { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "VREF control register"]
# [inline (always)]
pub const fn cr (self) -> crate :: common :: Reg < regs :: Cr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } } pub mod regs { # [doc = "VREF control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cr (pub u32) ; impl Cr { # [doc = "VREFBUF output level selection"]
# [inline (always)]
pub const fn vrefbuf_out_sel (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "VREFBUF output level selection"]
# [inline (always)]
pub fn set_vrefbuf_out_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "VREFBUF enable"]
# [inline (always)]
pub const fn vrefbuf_en (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "VREFBUF enable"]
# [inline (always)]
pub fn set_vrefbuf_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for Cr { # [inline (always)]
fn default () -> Cr { Cr (0) } } }